using KthulhuWantsMe.AutoGenerated;
using UnityEngine;

namespace KthulhuWantsMe.Source
{
    public static class LayerMasks
    {
        public static readonly int PlayerMask = LayerMask.GetMask(Layers.Player);
        public static readonly int EnemyMask = LayerMask.GetMask(Layers.Enemy);
        public static readonly int GroundMask = LayerMask.GetMask(Layers.Ground);
        public static readonly int IgnoreRaycastMask = LayerMask.GetMask(Layers.IgnoreRaycast);
        
        public static readonly int All = Physics.AllLayers & ~(1 << LayerMask.NameToLayer(Layers.IgnoreRaycast));
        public static readonly int Nothing = 0;
        
        public static readonly int GroundLayer = LayerMask.NameToLayer(Layers.Ground);
  
    }
}