
namespace KthulhuWantsMe.AutoGenerated
{
    public static class Layers
    {
		public const string Default = "Default";
		public const string TransparentFX = "TransparentFX";
		public const string IgnoreRaycast = "Ignore Raycast";
		public const string Water = "Water";
		public const string UI = "UI";
		public const string Player = "Player";
		public const string Enemy = "Enemy";
		public const string PlayerRoll = "PlayerRoll";
		public const string Ground = "Ground";
		public const string Item = "Item";
		public const string Interactable = "Interactable";
		public const string PlayerInteractionZone = "PlayerInteractionZone";
		public const string FadeableObject = "FadeableObject";

    }
}
