using System.IO;
using UnityEditor;
using UnityEngine;

namespace KthulhuWantsMe.Source.Editor
{
    public static class LayersAutoGeneration
    {
       private const string FolderPath = "KthulhuWantsMe/Source/AutoGenerated/";
       private const string Namespace = "KthulhuWantsMe.AutoGenerated";
       private const string FileName = "Layers";
        
        [MenuItem("Tools/Generate Layers")]
        private static void GenerateLayers()
        {
            if (!Directory.Exists(FolderPath))
                Directory.CreateDirectory(FolderPath);

            File.WriteAllText(Path.Combine(Application.dataPath, FolderPath) + $"{FileName}.cs", GenerateLayersFile());
            AssetDatabase.Refresh();
        }

        private static string GenerateLayersFile()
        {
            string[] layerNames = UnityEditorInternal.InternalEditorUtility.layers;

            return $@"
namespace {Namespace}
{{
    public static class Layers
    {{
{GenerateLayerConstants(layerNames)}
    }}
}}
";
        }

        private static string GenerateLayerConstants(string[] layerNames)
        {
            string layerConstants = "";
            foreach (string layerName in layerNames)
            {
                layerConstants += $"\t\tpublic const string {layerName.Replace(" ", "")} = \"{layerName}\";\n";
            }
            return layerConstants;
        }
       
    }
}